config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :tags, only: [:index, :show]
  resources :comments
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/author.rb
class Author < ApplicationRecord
  authenticates_with_sorcery!
  has_many :posts
  validates_confirmation_of :password, message: "should match confirmation", if: :password
  validates :password, length: { minimum: 3 }, if: -> { new_record? || changes[:crypted_password] }
  validates :password, confirmation: true, if: -> { new_record? || changes[:crypted_password] }
  validates :password_confirmation, presence: true, if: -> { new_record? || changes[:crypted_password] }

  validates :username, length: { minimum: 3 }

  validates :email, uniqueness: true, email_format: { message: 'has invalid format' }
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  before_action :require_login, except: [:new, :create]
  before_action :set_author, only: [:show, :edit, :update, :destroy]
  #before_action :zero_authors_or_authenticated, only: [:new, :create]
  # def zero_authors_or_authenticated
  #   unless Author.count == 0 || current_user
  #     redirect_to root_path
  #     return false
  #   end
  # end



  # GET /authors
  # GET /authors.json
  def index
    @authors = Author.all
  end

  # GET /authors/1
  # GET /authors/1.json
  def show
  end

  # GET /authors/new
  def new
    @author = Author.new
  end

  # GET /authors/1/edit
  def edit
  end

  # POST /authors
  # POST /authors.json
  def create
    @author = Author.new(author_params)

    respond_to do |format|
      if @author.save
        format.html { redirect_to @author, notice: 'Author was successfully created.' }
        format.json { render :show, status: :created, location: @author }
      else
        format.html { render :new }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /authors/1
  # PATCH/PUT /authors/1.json
  def update
    respond_to do |format|
      if @author.update(author_params)
        format.html { redirect_to @author, notice: 'Author was successfully updated.' }
        format.json { render :show, status: :ok, location: @author }
      else
        format.html { render :edit }
        format.json { render json: @author.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /authors/1
  # DELETE /authors/1.json
  def destroy
    @author.destroy
    respond_to do |format|
      format.html { redirect_to authors_url, notice: 'Author was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_author
      @author = Author.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def author_params
      params.require(:author).permit(:name, :username, :email, :password, :password_confirmation)
    end
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/views/authors/_form.html.erb
<%= form_with(model: author, local: true, :class => 'mui-form') do |form| %>
  <% if author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% author.errors.full_messages.each do |message| %>
        <li><div class="alert alert-danger" role="alert"> <<%= message %></li></div>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="mui-textfield">
    <%= form.label :Name %>
    <%= form.text_field :name, id: :name, required: true  %>
  </div>

  <div class="mui-textfield">
    <%= form.label :Username %>
    <%= form.text_field :username, id: :username, required: true  %>
  </div>

  <div class="mui-textfield">
    <%= form.label :Email %>
    <%= form.text_field :email, id: :author_email, required: true %>
  </div>

  <div class="mui-textfield">
    <%= form.label :Password %>
    <%= form.password_field :password, id: :author_password, required: true %>
  </div>

  <div class="mui-textfield">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation, id: :author_password_confirmation, required: :true %>
  </div>

  <div class="actions">
    <%= form.submit( 'Register', {:class => 'mui-btn mui-btn--primary'}) %>
  </div>
<% end %>

app/views/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form', author: @author %>

<%= link_to 'Show', @author %> |
<%= link_to 'Back', authors_path %>

app/views/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Username</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= author.username %></td>
        <td><%= author.email %></td>
        <td><%= link_to 'Show', author %></td>
        <td><%= link_to 'Edit', edit_author_path(author) %></td>
        <td><%= link_to 'Destroy', author, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_author_path %>

app/views/authors/new.html.erb
<div class="mui-container-fluid">
  <h1>Register New Author</h1>
  <div class="mui-row">
    <div class="mui-col-xs-12 mui-col-md-8 mx-auto">
        <div class="mui-panel my-3 justify-content">
          <%= render 'form', author: @author %>
        </div>
        <%= link_to 'Go Back', authors_path, :class => 'mui-btn mui-btn--raised' %>
    </div>
  </div>
</div>

app/views/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<p>
  <strong>Username:</strong>
  <%= @author.username %>
</p>
<p>
  <strong>Email:</strong>
  <%= @author.email %>
</p>


<%= link_to 'Edit', edit_author_path(@author) %> |
<%= link_to 'Back', authors_path %>