config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :tags, only: [:index, :show]
  resources :comments
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author
  has_many :comments, dependent: :delete_all
  has_many :taggings
  has_many :tags, through: :taggings
  has_attached_file :image
  has_attached_file :image, style: { medium: "300x300>", thumb: "64x64>"  }
  has_attached_file :image, :default_url => ":style/missing_avatar.jpg", style: { medium: "300x300>", thumb: "50x50" }
  validates_attachment_content_type :image, content_type: /^image\/(png|gif|jpeg|jpg)/

  def self.tagged_with(name)
    Tag.find_by!(name: name).posts
  end

  def self.tag_counts
    Tag.select('tags.*, count(taggings.tag_id) as count').joins(:taggings).group('taggings.tag_id')
  end

  def tag_list
    tags.map(&:name).join(', ')
  end

  def tag_list=(names)
    self.tags = names.split(',').map do |n|
      Tag.where(name: n.strip).first_or_create!
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: [:show, :edit, :update, :destroy, :post_owner]
  before_action :require_login, except: [:index, :show]
  before_action :post_owner, only: [:edit, :update, :destroy, :post_owner]

  def index
    #@posts = Post.order(created_at: :DESC)
    #@posts = Post.where(author_id: current_user)
    params[:tag] ? @posts = Post.tagged_with(params[:tag]) : @posts = Post.order(created_at: :DESC)
  end

  def show
   @post = Post.find(params[:id])
   @comment = Comment.new
   @comment.post_id = @post.id
  end

  def new
    @post = Post.new
    #@post = current_user.posts.build
  end

  def create
    @post = current_user.posts.build(post_params)
    #@post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post '#{@post.title}' has been Created !!!"
      redirect_to @post
    else
      render 'new'
    end
  end

  def edit
    @post = Post.find(params[:id])
  end
#@posts = Post.where(author_id: current_user)
def update
    @post = Post.find(params[:id])
    if @post.update(post_params)
      redirect_to @post
    else
      redirect_to posts_path
    end
end

def destroy
   @post = Post.find(params[:id])
   if @post.destroy
     flash[:success] = "Post '#{@post.title}' has been Successfully Deleted !!!"
     redirect_to posts_path
   else
     flash[:danger] = "Post '#{@post.title}' Did not Deleted.. !!!"
   end
end

  private
  def find_post
      @post = Post.find(params[:id])
  end

  def post_owner
     unless @post.author_id == current_user.id
      flash[:error] = 'Access Denied!! You are not The Author of this Post'
      redirect_to posts_path
     end
  end


  def post_params
    params.require(:post).permit(:title, :body, :image, :author, :tag_list, :tag, { tag_ids: [] }, :tag_ids)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
  def post_params
     params.require(:post).permit(:title, :body, :tag_list, :tag, { tag_ids: [] }, :tag_ids, :image, :author)
  end
end

app/views/posts/_comment.html.erb
<div class="mui-container-fluid">
  <div class="mui-row">
      <div class="mui-col-xs-12 mui-col-md-10 mx-auto">
          <div class="mui-panel my-3 justify-content">
            <p><strong>Comment By:</strong> <span class="text-primary"><%= comment.author.name %></span></p>
            <p class="comment"><%= comment.body %>
              <br>
              <span class="float-right mt-3">
                <% if comment.created_at != nil %>
                    Commented: <%= time_ago_in_words(comment.created_at) %> ago

                      <% if logged_in? %>
                        <%= button_to "X", [comment.post, comment],
                            method: :delete,
                            onclick: "return confirm('Are you sure?')",
                            remote: true,
                            class: 'mui-btn mui-btn--small mui-btn--danger mui-btn--fab ml-5' %>

                            <!-- %= button_to("Delete Post", {}, {:onclick => "return confirm('Are you sure?')", :method => :delete, :remote => true, :class => 'mui-btn mui-btn--danger'}) % -->
                      <% end %>
                <% end %>
              </span>
            </p>
          </div>
          <div class="mui-divider"></div>
      </div>
    </div>
</div>

app/views/posts/_create-form.html.erb
<% if @post.errors.any? %>
  <% @post.errors.full_messages.each do |msg| %>
      <div class="alert alert-danger" role="alert"> <%= msg %> </div>
  <% end %>
<% end %>
  <%= simple_form_for @post, :html => {multipart: true, :class => 'mui-form'} do |f|  %>
      <div class="mui-textfield">
        <%= f.text_field(:title, {:placeholder => 'Title', :required => true}) %>
      </div>
      <div class="mui-textfield">
        <%= f.text_area(:body, {:placeholder => 'Body', :required => true}) %>
      </div>
      <div class="mui-textfield">
        <!-- %= f.label :tag_list %-->
        <%= f.text_field(:tag_list, {:placeholder => 'Add New Tag List' }) %>
        <p>
          <span><i><small>Or Select From Tag IDs Below</small></i></span>
        </p>
      </div>
      <div class="mui-custom-select">
        <p>
         <%= f.input :tag_ids, as: :select, collection: Tag.order(:name), label_method: :name, input_html: {multiple: true, :class => 'chosen-select mui-select'} %>
       </p>
      </div>
      <p>
        <% if @post.image.exists? %>
            <%= image_tag @post.image.url(:medium) %><br/>
        <% end %>
        <%= f.label :image, "Attach a New Image" %><br />
        <%= f.file_field :image %>
      </p>
      <br>
      <p>
        <span><%= f.submit({:class => 'mui-btn mui-btn--primary'}) %></span>
          &nbsp;
        <span><%= link_to "Go Back To Posts", posts_path, {:class => 'mui-btn mui-btn--raised'} %></span>
      </p>
  <% end %>

app/views/posts/edit.html.erb
<div class="mui-container-fluid">
  <h1>Update This Post</h1>
  <div class="mui-row">
    <div class="mui-col-xs-12 mui-col-md-9 mx-auto">
        <div class="mui-panel my-3 justify-content">
          <%= render partial: 'create-form' %>
        </div>
    </div>
  </div>
</div>

app/views/posts/index.html.erb
<div class="mui-row">
  <% @posts.each do |post| %>
    <%= link_to post_path(post) do %>
      <div class="mui-col-xs-12 mui-col-md-4 mb-5">
          <div class="cardStyle card booking-card">
            <div class="view overlay">
              <%= image_tag post.image.url, class: 'card-img-top', alt: 'No Image' %>
              <a href="#!">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <div class="card-body">
              <h4 class="card-title font-weight-bolde">
                <%= link_to post.title, post_path(post), class: ' text-center post_title' %>
              </h4>
              Tags:
              <p>
                  <% post.tags.each do |tag| %>
                    <span class="trigger blue lighten-4">
                      <%= link_to tag.name, tag_path(tag) %>
                    </span>
                  <% end %>
              </p>
              <br>
              <p class="card-text"><%= post.body.truncate(30) %></p>
              <hr class="my-2">
              <i><%= link_to "Read More", post_path(post) %></i>
            </div>
          </div>
        </div>
     <% end %>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="mui-container-fluid">
  <h1>Create New Post</h1>
  <div class="mui-row">
    <div class="mui-col-xs-12 mui-col-md-9 mx-auto">
        <div class="mui-panel my-3 justify-content">
          <%= render 'create-form' %>
        </div>
    </div>
  </div>
</div>

app/views/posts/show.html.erb
<div class="mui-container-fluid">
  <div class="mui-row">
      <div class="mui-col-xs-12 mui-col-md-10 mx-auto">
          <div class="mui-panel my-3 justify-content">
            <h1 class="postTitle"><%= @post.title %></h1>
            <br>
            <p>
              Tags:
              <!-- <span class="trigger blue lighten-4"> -->
                <!--%= link_to tag.name, tag_path(tag) %-->
                <!--%= raw @post.tags.map(&:name).map { |tag| link_to tag, tag_path(tag) }.join(', ') %-->

              <!-- </span> -->
              <% @post.tags.each do |tag| %>
                <span class="trigger blue lighten-4">
                  <%= link_to tag.name, tag_path(tag) %>
                </span>
              <% end %>
            </p>
            <br>
            <p><%= image_tag @post.image.url, :class => "BloPostImg" %></p>
            <br>
            <p class="showBody"><%= @post.body %></p>
            <br>
            <p>Posted By: <b><%= @post.author.name %></b></p>
            <p>Posted: <b><%= time_ago_in_words @post.created_at %> ago</b> </p>
            <br>
            <div class="mui-divider"></div>
            <br>
            <% if logged_in? %>
              <div class="btn-group">
                <%= link_to "Back To Post", posts_path, :class => 'mui-btn mui-btn--small mui-btn--raised mr-1 rounded-0'  %>
                <%= link_to 'Edit Post', edit_post_path(@post), :class => 'mui-btn mui-btn--small mui-btn--primary mr-2 rounded-0' %>
                <%= button_to("Delete Post", {}, {:onclick => "return confirm('Are you sure?')", :method => :delete, :remote => true, :class => 'mui-btn mui-btn--small mui-btn--danger rounded-0'}) %>
                  <!-- %= button_to("Delete Post", {}, {:onclick => "return confirm('Are you sure?')", :method => :delete, :remote => true, :class => 'mui-btn mui-btn--danger'}) % -->
              </div>
            <% end %>
          </div>
          <br>
      </div>
  </div>
</div>
<br>
<h3>Comments (<%= @post.comments.size %>) </h3>
<%= render partial: 'posts/comment', collection: @post.comments.reverse %>

<div class="mui-container-fluid">
  <div class="mui-row">
      <div class="mui-col-xs-12 mui-col-md-10 mx-auto">
        <% if logged_in? %>
          <%= render partial: 'comments/form' %>
          <% else %>
          <h5><%= link_to "Login", login_path %> to Comment on this Post</h5>
        <% end %>
      </div>
  </div>
</div>