config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  resources :posts do
    resources :comments
  end
  resources :tags, only: [:index, :show]
  resources :comments
  resources :authors

  resources :author_sessions, only: [ :new, :create, :destroy ]

  get 'login'  => 'author_sessions#new'
  get 'logout' => 'author_sessions#destroy'
end

app/views/layouts/_footer.html.erb
<p>
  Copyright &copy;2020 All rights reserved | <i class="icon-heart" aria-hidden="true"></i> by <a href="https://kennice.org" target="_blank">Kennice Org</a>
</p>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
	  <div class="container-fluid">
    		<button type="button" id="sidebarCollapse" class="btn btn-primary">
    		  <i class="fa fa-bars"></i>
    		  <span class="sr-only">Toggle Menu</span>
    		</button>
    		<button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    			<i class="fa fa-bars"></i>
    		</button>
    		<div class="collapse navbar-collapse" id="navbarSupportedContent">
    		  <ul class="nav navbar-nav ml-auto">
						<% if logged_in? %>
	      			<li class="nav-item active">
	      				<%= link_to "Create New Post", new_post_path, class: "nav-link" %>
	      			</li>
						<% end %>
      			<li class="nav-item">
							<% if logged_in? %>
								 <%= link_to "Logout", logout_path, class: "nav-link"  %>
							 <% else %>
								 <%= link_to "Login", login_path, class: "nav-link"  %>
							 <% end %>
      			</li>
    		  </ul>
    		</div>
	  </div>
</nav>

app/views/layouts/_sidebar.html.erb
<nav id="sidebar">
				<div class="p-4 pt-5">
		  		<a class="img logo rounded-circle mb-5" <%= link_to image_tag("logo.png", alt: "logo"), '/', class: 'img' %></a>
				<ul class="list-unstyled components mb-5">
          <li class="<%= 'active' if current_page?(root_path) %>">
            <%= link_to "Home", root_path %>
          </li>
          <li class="<%= 'active' if current_page?(posts_path) %>">
            <%= link_to "Posts", posts_path %>
          </li>
						<% if logged_in? %>
							<li class="<%= 'active' if current_page?(new_post_path) %>">
								 <%= link_to "Create New Post", new_post_path %>
							 <% else %>
							 </li>
						 <% end %>
					<% if logged_in? %>
							<li class="<%= 'active' if current_page?(logout_path) %>">
								<%= link_to "Logout", logout_path %>
							</li>
							<% else %>
							<li class="<%= 'active' if current_page?(login_path) %>">
								<%= link_to "Login", login_path %>
							</li>
							<li class="<%= 'active' if current_page?(new_author_path) %>">
								<%= link_to "Register", new_author_path %>
							</li>
					<% end %>
        </ul>

					<div class="footer">
            <%= render "layouts/footer" %>
					</div>

				  </div>
			</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
    <% if logged_in? %>
       <%= "#{current_user.name}" %>
     <% else %>
       RubyBlog
     <% end %>
    </title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= stylesheet_link_tag 'application','https://fonts.googleapis.com/css2?family=Exo+2:wght@100;200;300;600;700;800&family=Ubuntu:wght@300;400;500;700&display=swap" rel="stylesheet', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'application','https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/material-design-iconic-font/2.2.0/css/material-design-iconic-font.min.css' , media: 'all', 'data-turbolinks-track': 'reload'%>
    <%= stylesheet_link_tag 'https://cdnjs.cloudflare.com/ajax/libs/muicss/0.9.41/css/mui.min.css', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://cdnjs.cloudflare.com/ajax/libs/muicss/0.9.41/js/mui.min.js', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="wrapper d-flex align-items-stretch">
       <%= render "layouts/sidebar" %>

       <div id="content" class="p-4 p-md-5">
         <%= render "layouts/header" %>
         <div class="mb-4">
           <% flash.each do |key, value| %>
               <span class="<%= flash_class(key) %>">
                     <%= value %>
               </span>
               <br>
           <% end %>
            <br>
           <%= yield %>
         </div>
       </div>
     </div>


     <script>
       $(document).on('ready page:load', function () {
         $('#post_tag_ids').chosen({
           allow_single_deselect: true,
           width: '100%'
         })
       });
     </script>
    <%= javascript_include_tag "jquery.min.js" %>
    <%= javascript_include_tag "popper.js" %>
    <%= javascript_include_tag "bootstrap.min.js" %>
    <%= javascript_include_tag "main" %>
  </body>
</html>